### ISSUE TITLE
Linux install Doc dir: gPodder not gpodder

### ISSUE THREAD

**Issue by strukturart** [gpodder/gpodder.github.io#21]
Hello,

https://gpodder.github.io/docs/run-from-git.html

after starting gPodder the first time a new dir is creating gPodder.
Does it really need 2 directories gpodder and gPodder, or is it a bug in the Installtions doc ?

**Comment by elelay** [comment]
Hi,
 - `~/gPodder` is the data folder, where gPodder stores stores its database, settings and downloads (you'll see 1 folder per podcast in Downloads);
 - `gpodder` is where gPodder's code has been checked-out by `git clone`.
So, yes: 2 directories, for 2 different purposes.
