### ISSUE TITLE
Broken link in "Reporting Download Bugs" docs page

### ISSUE THREAD

**Issue by hallamjeff** [gpodder/gpodder.github.io#28]
In the documentation page regarding "[Reporting Download Bugs](https://gpodder.github.io/docs/reporting-download-bugs.html)" there is a link to a screenshot example of what the request and response headers should look like. The current link location, [http://khan.thpinfo.com/~thp/images/follow-tcp-stream.png](http://khan.thpinfo.com/~thp/images/follow-tcp-stream.png) is a dead link.

**Comment by thp** [comment]
I would need to dig this one out from the archives.

**Comment by hallamjeff** [comment]
Would another option be to reconstruct a new screenshot by running tcpdump and wireshark as the article describes? The only reason I hesitate to contribute it myself is that I don't know what it should actually look like.

**Comment by thp** [comment]
I found the picture and I added it directly to the repo, this might not
have been clear from the automatic closing that Github does, but the
picture should now be visible on the gpodder.github.io page (you might need
to hit refresh).

Jeff Hallam <notifications@github.com> schrieb am So., 12. Apr. 2020, 16:24:
