### ISSUE TITLE
Registration

### ISSUE THREAD

**Issue by c-git** [gpodder/gpodder.github.io#49]
Hi,

I'm trying to [register for an account](https://gpodder.net/register/) and wanted to know if you are no longer accepting registrations or if I should just keep trying?

I get "500 - Internal server error. The service is currently overloaded. Please try again later or contact us." error message when I try to register. 

![image](https://github.com/gpodder/gpodder.github.io/assets/43485962/557ae5f2-547a-4b8d-b2da-a7e5543f6ea2)

**Comment by auouymous** [comment]
The gpodder.net service is managed over at https://github.com/gpodder/mygpo/issues, and has been unstable for a couple years.

**Comment by c-git** [comment]
Thank you
