### ISSUE TITLE
Extensions docs are not reachable from home page

### ISSUE THREAD

**Issue by masoudd** [gpodder/gpodder.github.io#51]
I'm sorry if I'm mistaken but I can't find a way to reach https://gpodder.github.io/docs/extensions from the home page or docs page. Where do you think it would be right to add a link to it? I think link to it should be inserted as the third link here: https://gpodder.github.io/docs/ after FAQ and before sitemap

**Comment by auouymous** [comment]
docs -> user manual -> gpodder extensions -> "this page", or am I misunderstanding the question?

**Comment by masoudd** [comment]
Yes my mistake sorry
