### ISSUE TITLE
What should happen with the "Web Services/*" pages?

### ISSUE THREAD

**Issue by adamvoss** [gpodder/gpodder.github.io#9]
The [Web Services](http://wiki.gpodder.org/w/index.php?title=Special%3APrefixIndex&prefix=Web+Services&namespace=0) pages are believed to be the only pages not migrated from the old Wiki.

@stefankoegl Needs to clarify what should happen with these pages pages.

Moved from gpodder/gpodder#218.

**Comment by thp** [comment]
Probably the best would be to convert them into some documentation format (Sphinx) and ship it as part of gpodder.net, but ultimately that's up to @stefankoegl to decide :)

**Comment by stefankoegl** [comment]
I have now integrated all gpodder.net related pages into the gpodder.net docs, and linked the new pages from the wiki.

The only page that remains is http://wiki.gpodder.org/wiki/Web_Services/API/Reference, which should probably go into [gpodder/mygpoclient](https://github.com/gpodder/mygpoclient).

**Comment by stefankoegl** [comment]
See gpodder/mygpoclient#13 for the remaining part.

**Comment by adamvoss** [comment]
Awesome!  @thp Unless something was overlooked at an earlier date, this should mean all content has been re-homed away from wiki.gpodder.org, and that it now exists only to direct users to the new content homes.

@stefankoegl  I don't know the best place to document this task but another task worth pursuing some time would be to update all the links to wiki.gpodder.org on gpodder.net

**Comment by thp** [comment]
Cool stuff! Thanks @stefankoegl and @adamvoss :)
